<?php
/*
 * @category   Fishpig
 * @package    Fishpig_AttributeSplashPro
 * @author     Ben Tideswell <ben@fishpig.co.uk>
 */
?>
<script type="text/javascript">
//<![CDATA[
	function FPSplashPro_importOpen()  {  $('splash-import').addClassName('show');    }
	function FPSplashPro_importClose() {  $('splash-import').removeClassName('show'); }
//]]>
</script>
<div id="splash-import">
	<div class="shadow" onclick="FPSplashPro_importClose();"></div>
	<div class="inner">
		<div class="content-header">
			<table cellspacing="0">
				<tbody>
					<tr>
						<td><h3><?php echo $this->__('Import Splash Pro Pages') ?></h3></td>	
					</tr>
				</tbody>
			</table>
		</div>
		<form method="POST" action="<?php echo $this->getUrl('*/splash/import') ?>" id="splashimportform"  enctype="multipart/form-data">
			<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey()  ?>"/>
			<div class="entry-edit">
				<div class="fieldset fieldset-wide" id="group_fields49">
					<div class="hor-scroll">
						<table class="form-list" cellspacing="0">
							<tbody>
								<tr>
									<td class="label"><label for="is_karwan_test_attribute">CSV File</label></td>
									<td class="value">
										<input type="file" name="splash_import" />
									</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
				<div class="buttons-set">
					<button type="submit" class="button"><span>Upload</span></button>
				</div>
			</div>
		</form>
	</div>
</div>
<style type="text/css">
#splash-import { position: absolute; top: 0; left: 0; z-index: 99998;  width: 100%; height: 100%; display: none; }
#splash-import.show { display: block; }
#splash-import .shadow { position: absolute; top: 0; left: 0; background: #000; z-index: 99999; opacity: 0.3; width: 100%; height: 100%; }
#splash-import .inner { position: relative; z-index: 999999; background: #fff; width: 600px; margin: 50px auto 0; padding: 20px; }
</style>